
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.attendance_information_groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.attendance_information_groupBox.setGeometry(QtCore.QRect(450, 40, 301, 391))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.attendance_information_groupBox.setFont(font)
        self.attendance_information_groupBox.setObjectName("attendance_information_groupBox")
        self.name_confirm_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.name_confirm_label.setGeometry(QtCore.QRect(20, 70, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.name_confirm_label.setFont(font)
        self.name_confirm_label.setObjectName("name_confirm_label")
        self.department_confirm_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.department_confirm_label.setGeometry(QtCore.QRect(20, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.department_confirm_label.setFont(font)
        self.department_confirm_label.setObjectName("department_confirm_label")
        self.time_confirm_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.time_confirm_label.setGeometry(QtCore.QRect(20, 220, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.time_confirm_label.setFont(font)
        self.time_confirm_label.setObjectName("time_confirm_label")
        self.date_confirm_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.date_confirm_label.setGeometry(QtCore.QRect(20, 300, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.date_confirm_label.setFont(font)
        self.date_confirm_label.setObjectName("date_confirm_label")
        self.name_edit_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.name_edit_label.setGeometry(QtCore.QRect(90, 70, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.name_edit_label.setFont(font)
        self.name_edit_label.setObjectName("name_edit_label")
        self.department_edit_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.department_edit_label.setGeometry(QtCore.QRect(130, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.department_edit_label.setFont(font)
        self.department_edit_label.setObjectName("department_edit_label")
        self.time_edit_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.time_edit_label.setGeometry(QtCore.QRect(80, 220, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.time_edit_label.setFont(font)
        self.time_edit_label.setObjectName("time_edit_label")
        self.date_edit_label = QtWidgets.QLabel(parent=self.attendance_information_groupBox)
        self.date_edit_label.setGeometry(QtCore.QRect(80, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.date_edit_label.setFont(font)
        self.date_edit_label.setObjectName("date_edit_label")
        self.retake_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.retake_Button.setGeometry(QtCore.QRect(470, 460, 101, 41))
        self.retake_Button.setObjectName("retake_Button")
        self.confirmation_cancel_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirmation_cancel_Button.setGeometry(QtCore.QRect(620, 460, 101, 41))
        self.confirmation_cancel_Button.setObjectName("confirmation_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.countdown_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.countdown_label.setGeometry(QtCore.QRect(730, 460, 50, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.countdown_label.setFont(font)
        self.countdown_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.countdown_label.setObjectName("countdown_label")
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.camera_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.camera_label.setGeometry(QtCore.QRect(20, 40, 400, 350))
        self.camera_label.setObjectName("camera_label")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.attendance_information_groupBox.setTitle(_translate("MainWindow", "Attendee\'s Information"))
        self.name_confirm_label.setText(_translate("MainWindow", "Name : "))
        self.department_confirm_label.setText(_translate("MainWindow", "Department :"))
        self.time_confirm_label.setText(_translate("MainWindow", "Time :"))
        self.date_confirm_label.setText(_translate("MainWindow", "Date :"))
        self.name_edit_label.setText(_translate("MainWindow", "Label"))
        self.department_edit_label.setText(_translate("MainWindow", "Label"))
        self.time_edit_label.setText(_translate("MainWindow", "Label"))
        self.date_edit_label.setText(_translate("MainWindow", "Label"))
        self.retake_Button.setText(_translate("MainWindow", "Retake"))
        self.confirmation_cancel_Button.setText(_translate("MainWindow", "Confirm"))
        self.countdown_label.setText("5")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
